In [1]:
import numpy as np

In [2]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
a = np.array([[0, 2, 3], [4, 5, 6, 7]])
a

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
a = np.array([[0, "John", 2, 3], [4, 5, 6, 7]])
a

array([['0', 'John', '2', '3'],
       ['4', '5', '6', '7']], dtype='<U11')

In [ ]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
a.shape

(2, 4)

In [ ]:
a[1, 3]

7

In [ ]:
a[1, 2] = 8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [ ]:
a[0]

array([0, 1, 2, 3])

In [ ]:
a[1]

array([4, 5, 8, 7])

In [ ]:
b = np.array([3, 5])

In [ ]:
b

array([3, 5])